config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get "documents/home"
  post "documents/query"

  resources :documents
  resources :folders

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "documents#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :file
  belongs_to :folder
end

app/models/folder.rb
class Folder < ApplicationRecord
    attribute :path, :string
    has_many :documents
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :folders
  has_many :documents, through: :folders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @folders = current_user.folders
  end

  def query
    draw = params[:draw].to_i
    start = params[:start].to_i
    length = params[:length].to_i
    search_value = params.dig(:search, :value)
    fields = params[:columns].map { |column| column[:name] }
    #fields = ["filename", "type", "size", "created_at", "updated_at"]

    order_by = params.dig(:order, 0, :name) || 'folder_id'
    order_direction = params.dig(:order, 0, :dir) || 'asc'

    @documents = current_user.documents 
    total = @documents.count

    if order_by == 'id'
      @documents = @documents.order("#{order_by} #{order_direction}")
    end

    @documents = @documents.map do |document|
      get_metadata(document)
    end

    if search_value.present?
      @documents = @documents.select do |document|
        document[:id].to_s.downcase.include?(search_value.downcase) ||
        document[:filename].downcase.include?(search_value.downcase) ||
        document[:type].downcase.include?(search_value.downcase)
      end
    end
    total_filtered = @documents.count

    if fields.include?(order_by)
      @documents = order_documents(@documents, order_by, order_direction)
    end

    if length > 0
      @documents = @documents[start, length]
    end
 
    output = {
      draw: draw,
      recordsTotal: total,
      recordsFiltered: total_filtered,
      data: @documents
    }

    render json: output, location: @user
  end

  def home
    index
  end

  def new
    @document = current_user.documents
    @folders = current_user.folders
  end

  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.save
        format.html { render action: "show" }
        format.js   {}
        format.json { render json: get_metadata(@document), location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    #@document = Document.new(document_params)
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.js   {}
        format.json { render json: @document, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def document_params
    params.require(:document).permit(:folder_id, :file)
  end

  def get_metadata(document)
    {
      DT_RowId: "row_#{document.id}",
      id: document.id,
      filename: document.file.filename.to_s,
      type: document.file.content_type,
      size: document.file.byte_size,
      created_at: document.created_at,
      updated_at: document.updated_at,
      folder_id: document.folder.id,
      folder_path: document.folder.path,
#      url: url_for(document.file?) || nil
    }
  end

  def order_documents(documents, order_by, order_direction)
    if order_direction.to_s.downcase == "desc"
      documents = @documents.sort_by do |document|
        [-document[order_by.to_sym]]
      end
    else
      documents = @documents.sort_by do |document|
        [document[order_by.to_sym]]
      end
    end

    return documents
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @folders = current_user.folders
    end

    def new
        @folder = Folder.new
        @users = User.all
    end

    def create
        @folder = Folder.new(folder_params)
        @user_id = current_user.id if user_signed_in?

        @folder.user_id = @user_id
    
        respond_to do |format|
          if @folder.save
            format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
            format.js   {}
            format.json { render json: @folde/r, status: :created, location: @user }
          else
            format.html { render action: "new" }
            format.json { render json: @folder.errors, status: :unprocessable_entity }
          end
        end
    end

    def show
    end

    private

    def folder_params
        params.require(:folder).permit(:path)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    def create
      super do |resource|
        if resource.persisted?  # Check if the user was saved successfully
            @folder = Folder.new
            user_id = resource.id

            @folder.path = "/"
            @folder.user_id = user_id

            @folder.save()
        end
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/folder_helper.rb
module FolderHelper
end

app/views/documents/home.html.erb
<h1>Uploaded Files</h1>

<% if @documents.any? %>
  <ul>
    <% @documents.each do |document| %>
      <li>
        <%= document.file.filename %> <!-- Display the filename -->
        <%= link_to 'Download', url_for(document.file) %> <!-- Link to download the file -->
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No files have been uploaded yet.</p>
<% end %>

<%= link_to 'Upload New File', new_document_path %> <!-- Link to the new upload form -->

app/views/documents/index.html.erb
<h1>Uploaded Files</h1>

<%= link_to 'Create New Folder', new_folder_path %>
<%= link_to 'Upload File', new_document_path %>

<select class="form-select" aria-label="Default select example">
  <option selected>Select a folder</option>
  <% @folders.each do |folder| %>
      <option value=<%= folder.id %>><%= folder.path %></option>
  <% end %>
</select>

<table id="table-documents" class="m-3">
    <thead>
      <tr>
        <th class="notexport"></th>
        <th>ID</th>
        <th>FOLDER ID</th>
        <th>FOLDER</th>
        <th>FILENAME</th>
        <th>TYPE</th>
        <th>SIZE</th>
        <th>CREATED AT</th>
        <th>UPDATED AT</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>


<%= javascript_include_tag "documents_table.js" %>

app/views/documents/new.html.erb
<h1>Documents#index</h1>
<p>Find me in app/views/documents/index.html.erb</p>

<%= form_with model: @document, remote: true, multipart: true do |form| %>
  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file, required: true %>
  </div>
  
  <div class="field">
    <%= form.label :folder_id, "Select Folder" %>
    <%= form.collection_select :folder_id, @folders, :id, :path, prompt: "Choose a folder", required: true %>
  </div>

  <%= form.submit 'Upload File' %>
<% end %>

app/views/documents/show.html.erb
<h1><%= @document.file.filename %></h1>  <!-- Supponendo che il documento abbia un titolo -->
<%= link_to 'Download', url_for(@document.file) if @document.file.attached? %>
<%= link_to 'Edit', edit_document_path(@document) %>
<%= link_to 'Back', documents_path %>

app/views/folders/index.html.erb
<h1>Folders</h1>

<% if @folders.any? %>
  <ul>
    <% @folders.each do |folder| %>
      <li>
        <%= folder.path %> <!-- Display the filename -->
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No folders have been uploaded yet.</p>
<% end %>

<%= link_to 'Create New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>Create Folder</h1>

<%= form_with model: @folder, remote: true, multipart: true do |form| %>
  <div class="field">
      <%= form.label :path %>
    <%= form.text_field :path %>
  </div>

  <%= form.submit 'Add Folder' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rh Drive" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <link href="https://cdn.datatables.net/v/bs5/jszip-3.10.1/dt-2.1.8/af-2.7.0/b-3.1.2/b-colvis-3.1.2/b-html5-3.1.2/b-print-3.1.2/cr-2.0.4/date-1.5.4/fc-5.0.4/fh-4.0.1/kt-2.12.1/r-3.0.3/rg-1.5.0/rr-1.5.0/sc-2.4.3/sb-1.8.1/sp-2.3.3/sl-2.1.0/sr-1.4.1/datatables.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">rh-drive</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link', data: { turbo: false } %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/v/bs5/jszip-3.10.1/dt-2.1.8/af-2.7.0/b-3.1.2/b-colvis-3.1.2/b-html5-3.1.2/b-print-3.1.2/cr-2.0.4/date-1.5.4/fc-5.0.4/fh-4.0.1/kt-2.12.1/r-3.0.3/rg-1.5.0/rr-1.5.0/sc-2.4.3/sb-1.8.1/sp-2.3.3/sl-2.1.0/sr-1.4.1/datatables.min.js"></script>

    
    <%= javascript_include_tag "utils.js" %>
  </body>
</html>